-- Oasis Piercing — Categorías restantes + 140 productos (20 por categoría)
-- Nariz, Ombligo, Ceja, Labio, Industrial, Lengua, Pesones
-- Imagen temporal: foto de categoría (reemplazar desde /admin/productos)

BEGIN;

INSERT INTO categorias (nombre, slug, descripcion, activo)
SELECT v.nombre, v.slug, v.descripcion, TRUE
FROM (
  VALUES
    ('Nariz', 'nariz', 'Piercings para nariz: nostril, septum, clicker y más.'),
    ('Ombligo', 'ombligo', 'Piercings para ombligo: curved barbell, cadenas y colgantes.'),
    ('Ceja', 'ceja', 'Piercings para ceja: curved, straight y micro barbell.'),
    ('Labio', 'labio', 'Piercings para labio: labret, monroe, medusa y más.'),
    ('Industrial', 'industrial', 'Piercings industrial: barbells rectos y diseños statement.'),
    ('Lengua', 'lengua', 'Piercings para lengua: barbells, gemas y anodizado.'),
    ('Pesones', 'pesones', 'Piercings para pesones: barbell, aro y escudo.')
) AS v(nombre, slug, descripcion)
WHERE NOT EXISTS (SELECT 1 FROM categorias c WHERE c.slug = v.slug);

INSERT INTO productos (nombre, codigo, tipo, material, descripcion, precio, imagen, stock, slug, activo)
SELECT v.nombre, v.codigo, v.tipo, v.material, v.descripcion, v.precio, v.imagen, v.stock, v.slug, v.activo
FROM (
  VALUES
    ('Aro Dorado con Ópalo', 'OP-NAR-001', 'Nostril', 'Titanio G23 implant-grade · Libre de alérgenos · Hipoalergénico', 'Aro Dorado con Ópalo de la colección Nariz. Diseño tipo Nostril elaborado en Titanio G23 implant-grade. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 22000, '/images/categorias/nariz.png', 10, 'aro-dorado-con-opalo', TRUE),
    ('Septum Clicker Titanio', 'OP-NAR-002', 'Septum', 'Acero 316L quirúrgico · Oro PVD 18k · Sin níquel', 'Septum Clicker Titanio de la colección Nariz. Diseño tipo Septum elaborado en Acero 316L quirúrgico. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 24500, '/images/categorias/nariz.png', 10, 'septum-clicker-titanio', TRUE),
    ('Stud L-shape con Perla', 'OP-NAR-003', 'L-shape', 'Titanio G23 · Zirconia cúbica AAA · Anodizado', 'Stud L-shape con Perla de la colección Nariz. Diseño tipo L-shape elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 27000, '/images/categorias/nariz.png', 10, 'stud-l-shape-con-perla', TRUE),
    ('Hoop Nostril Delgado', 'OP-NAR-004', 'Hoop', 'Acero 316L · Cristal Swarovski · 14g estándar', 'Hoop Nostril Delgado de la colección Nariz. Diseño tipo Hoop elaborado en Acero 316L. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 29500, '/images/categorias/nariz.png', 10, 'hoop-nostril-delgado', TRUE),
    ('Clicker Flor Zirconia', 'OP-NAR-005', 'Clicker', 'Titanio G23 · Disco plano interno · Cierre seguro', 'Clicker Flor Zirconia de la colección Nariz. Diseño tipo Clicker elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 32000, '/images/categorias/nariz.png', 10, 'clicker-flor-zirconia', TRUE),
    ('Pin Dorado Micro', 'OP-NAR-006', 'Pin', 'Titanio G23 implant-grade · Libre de alérgenos · Hipoalergénico', 'Pin Dorado Micro de la colección Nariz. Diseño tipo Pin elaborado en Titanio G23 implant-grade. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 23800, '/images/categorias/nariz.png', 10, 'pin-dorado-micro', TRUE),
    ('Septum Herradura', 'OP-NAR-007', 'Septum Falso', 'Acero 316L quirúrgico · Oro PVD 18k · Sin níquel', 'Septum Herradura de la colección Nariz. Diseño tipo Septum Falso elaborado en Acero 316L quirúrgico. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 26300, '/images/categorias/nariz.png', 10, 'septum-herradura', TRUE),
    ('Bridge Barbell Mini', 'OP-NAR-008', 'Bridge', 'Titanio G23 · Zirconia cúbica AAA · Anodizado', 'Bridge Barbell Mini de la colección Nariz. Diseño tipo Bridge elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 28800, '/images/categorias/nariz.png', 10, 'bridge-barbell-mini', TRUE),
    ('Nostril Mariposa', 'OP-NAR-009', 'Nostril', 'Acero 316L · Cristal Swarovski · 14g estándar', 'Nostril Mariposa de la colección Nariz. Diseño tipo Nostril elaborado en Acero 316L. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 31300, '/images/categorias/nariz.png', 10, 'nostril-mariposa', TRUE),
    ('Septum Luna Creciente', 'OP-NAR-010', 'Septum', 'Titanio G23 · Disco plano interno · Cierre seguro', 'Septum Luna Creciente de la colección Nariz. Diseño tipo Septum elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 33800, '/images/categorias/nariz.png', 10, 'septum-luna-creciente', TRUE),
    ('Aro Dorado con Ópalo Ed. 11', 'OP-NAR-011', 'L-shape', 'Titanio G23 implant-grade · Libre de alérgenos · Hipoalergénico', 'Aro Dorado con Ópalo Ed. 11 de la colección Nariz. Diseño tipo L-shape elaborado en Titanio G23 implant-grade. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 25600, '/images/categorias/nariz.png', 10, 'aro-dorado-con-opalo-ed-11-11', TRUE),
    ('Septum Clicker Titanio Ed. 12', 'OP-NAR-012', 'Hoop', 'Acero 316L quirúrgico · Oro PVD 18k · Sin níquel', 'Septum Clicker Titanio Ed. 12 de la colección Nariz. Diseño tipo Hoop elaborado en Acero 316L quirúrgico. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 28100, '/images/categorias/nariz.png', 10, 'septum-clicker-titanio-ed-12-12', TRUE),
    ('Stud L-shape con Perla Ed. 13', 'OP-NAR-013', 'Clicker', 'Titanio G23 · Zirconia cúbica AAA · Anodizado', 'Stud L-shape con Perla Ed. 13 de la colección Nariz. Diseño tipo Clicker elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 30600, '/images/categorias/nariz.png', 10, 'stud-l-shape-con-perla-ed-13-13', TRUE),
    ('Hoop Nostril Delgado Ed. 14', 'OP-NAR-014', 'Pin', 'Acero 316L · Cristal Swarovski · 14g estándar', 'Hoop Nostril Delgado Ed. 14 de la colección Nariz. Diseño tipo Pin elaborado en Acero 316L. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 33100, '/images/categorias/nariz.png', 10, 'hoop-nostril-delgado-ed-14-14', TRUE),
    ('Clicker Flor Zirconia Ed. 15', 'OP-NAR-015', 'Septum Falso', 'Titanio G23 · Disco plano interno · Cierre seguro', 'Clicker Flor Zirconia Ed. 15 de la colección Nariz. Diseño tipo Septum Falso elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 35600, '/images/categorias/nariz.png', 10, 'clicker-flor-zirconia-ed-15-15', TRUE),
    ('Pin Dorado Micro Ed. 16', 'OP-NAR-016', 'Bridge', 'Titanio G23 implant-grade · Libre de alérgenos · Hipoalergénico', 'Pin Dorado Micro Ed. 16 de la colección Nariz. Diseño tipo Bridge elaborado en Titanio G23 implant-grade. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 27400, '/images/categorias/nariz.png', 10, 'pin-dorado-micro-ed-16-16', TRUE),
    ('Septum Herradura Ed. 17', 'OP-NAR-017', 'Nostril', 'Acero 316L quirúrgico · Oro PVD 18k · Sin níquel', 'Septum Herradura Ed. 17 de la colección Nariz. Diseño tipo Nostril elaborado en Acero 316L quirúrgico. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 29900, '/images/categorias/nariz.png', 10, 'septum-herradura-ed-17-17', TRUE),
    ('Bridge Barbell Mini Ed. 18', 'OP-NAR-018', 'Septum', 'Titanio G23 · Zirconia cúbica AAA · Anodizado', 'Bridge Barbell Mini Ed. 18 de la colección Nariz. Diseño tipo Septum elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 32400, '/images/categorias/nariz.png', 10, 'bridge-barbell-mini-ed-18-18', TRUE),
    ('Nostril Mariposa Ed. 19', 'OP-NAR-019', 'L-shape', 'Acero 316L · Cristal Swarovski · 14g estándar', 'Nostril Mariposa Ed. 19 de la colección Nariz. Diseño tipo L-shape elaborado en Acero 316L. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 34900, '/images/categorias/nariz.png', 10, 'nostril-mariposa-ed-19-19', TRUE),
    ('Septum Luna Creciente Ed. 20', 'OP-NAR-020', 'Hoop', 'Titanio G23 · Disco plano interno · Cierre seguro', 'Septum Luna Creciente Ed. 20 de la colección Nariz. Diseño tipo Hoop elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 37400, '/images/categorias/nariz.png', 10, 'septum-luna-creciente-ed-20-20', TRUE),
    ('Curved Barbell con Zirconia', 'OP-OMB-001', 'Curved Barbell', 'Titanio G23 implant-grade · Libre de alérgenos · Hipoalergénico', 'Curved Barbell con Zirconia de la colección Ombligo. Diseño tipo Curved Barbell elaborado en Titanio G23 implant-grade. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 38000, '/images/categorias/Ombligo.png', 10, 'curved-barbell-con-zirconia', TRUE),
    ('Ombligo Cadena con Perlas', 'OP-OMB-002', 'Cadena', 'Acero 316L quirúrgico · Oro PVD 18k · Sin níquel', 'Ombligo Cadena con Perlas de la colección Ombligo. Diseño tipo Cadena elaborado en Acero 316L quirúrgico. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 40500, '/images/categorias/Ombligo.png', 10, 'ombligo-cadena-con-perlas', TRUE),
    ('Dangle Cristal Largo', 'OP-OMB-003', 'Dangle', 'Titanio G23 · Zirconia cúbica AAA · Anodizado', 'Dangle Cristal Largo de la colección Ombligo. Diseño tipo Dangle elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 43000, '/images/categorias/Ombligo.png', 10, 'dangle-cristal-largo', TRUE),
    ('Reverse Ombligo Dorado', 'OP-OMB-004', 'Reverse', 'Acero 316L · Cristal Swarovski · 14g estándar', 'Reverse Ombligo Dorado de la colección Ombligo. Diseño tipo Reverse elaborado en Acero 316L. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 45500, '/images/categorias/Ombligo.png', 10, 'reverse-ombligo-dorado', TRUE),
    ('Joya Colgante Luna', 'OP-OMB-005', 'Joya Colgante', 'Titanio G23 · Disco plano interno · Cierre seguro', 'Joya Colgante Luna de la colección Ombligo. Diseño tipo Joya Colgante elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 48000, '/images/categorias/Ombligo.png', 10, 'joya-colgante-luna', TRUE),
    ('Flor de Zirconia Ombligo', 'OP-OMB-006', 'Flor', 'Titanio G23 implant-grade · Libre de alérgenos · Hipoalergénico', 'Flor de Zirconia Ombligo de la colección Ombligo. Diseño tipo Flor elaborado en Titanio G23 implant-grade. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 39800, '/images/categorias/Ombligo.png', 10, 'flor-de-zirconia-ombligo', TRUE),
    ('Corazón Rosa PVD', 'OP-OMB-007', 'Corazón', 'Acero 316L quirúrgico · Oro PVD 18k · Sin níquel', 'Corazón Rosa PVD de la colección Ombligo. Diseño tipo Corazón elaborado en Acero 316L quirúrgico. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 42300, '/images/categorias/Ombligo.png', 10, 'corazon-rosa-pvd', TRUE),
    ('Estrella Brillante', 'OP-OMB-008', 'Estrella', 'Titanio G23 · Zirconia cúbica AAA · Anodizado', 'Estrella Brillante de la colección Ombligo. Diseño tipo Estrella elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 44800, '/images/categorias/Ombligo.png', 10, 'estrella-brillante', TRUE),
    ('Barbell Ombligo Ópalo', 'OP-OMB-009', 'Curved Barbell', 'Acero 316L · Cristal Swarovski · 14g estándar', 'Barbell Ombligo Ópalo de la colección Ombligo. Diseño tipo Curved Barbell elaborado en Acero 316L. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 47300, '/images/categorias/Ombligo.png', 10, 'barbell-ombligo-opalo', TRUE),
    ('Cadena Triple Gema', 'OP-OMB-010', 'Cadena', 'Titanio G23 · Disco plano interno · Cierre seguro', 'Cadena Triple Gema de la colección Ombligo. Diseño tipo Cadena elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 49800, '/images/categorias/Ombligo.png', 10, 'cadena-triple-gema', TRUE),
    ('Curved Barbell con Zirconia Ed. 11', 'OP-OMB-011', 'Dangle', 'Titanio G23 implant-grade · Libre de alérgenos · Hipoalergénico', 'Curved Barbell con Zirconia Ed. 11 de la colección Ombligo. Diseño tipo Dangle elaborado en Titanio G23 implant-grade. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 41600, '/images/categorias/Ombligo.png', 10, 'curved-barbell-con-zirconia-ed-11-11', TRUE),
    ('Ombligo Cadena con Perlas Ed. 12', 'OP-OMB-012', 'Reverse', 'Acero 316L quirúrgico · Oro PVD 18k · Sin níquel', 'Ombligo Cadena con Perlas Ed. 12 de la colección Ombligo. Diseño tipo Reverse elaborado en Acero 316L quirúrgico. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 44100, '/images/categorias/Ombligo.png', 10, 'ombligo-cadena-con-perlas-ed-12-12', TRUE),
    ('Dangle Cristal Largo Ed. 13', 'OP-OMB-013', 'Joya Colgante', 'Titanio G23 · Zirconia cúbica AAA · Anodizado', 'Dangle Cristal Largo Ed. 13 de la colección Ombligo. Diseño tipo Joya Colgante elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 46600, '/images/categorias/Ombligo.png', 10, 'dangle-cristal-largo-ed-13-13', TRUE),
    ('Reverse Ombligo Dorado Ed. 14', 'OP-OMB-014', 'Flor', 'Acero 316L · Cristal Swarovski · 14g estándar', 'Reverse Ombligo Dorado Ed. 14 de la colección Ombligo. Diseño tipo Flor elaborado en Acero 316L. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 49100, '/images/categorias/Ombligo.png', 10, 'reverse-ombligo-dorado-ed-14-14', TRUE),
    ('Joya Colgante Luna Ed. 15', 'OP-OMB-015', 'Corazón', 'Titanio G23 · Disco plano interno · Cierre seguro', 'Joya Colgante Luna Ed. 15 de la colección Ombligo. Diseño tipo Corazón elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 51600, '/images/categorias/Ombligo.png', 10, 'joya-colgante-luna-ed-15-15', TRUE),
    ('Flor de Zirconia Ombligo Ed. 16', 'OP-OMB-016', 'Estrella', 'Titanio G23 implant-grade · Libre de alérgenos · Hipoalergénico', 'Flor de Zirconia Ombligo Ed. 16 de la colección Ombligo. Diseño tipo Estrella elaborado en Titanio G23 implant-grade. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 43400, '/images/categorias/Ombligo.png', 10, 'flor-de-zirconia-ombligo-ed-16-16', TRUE),
    ('Corazón Rosa PVD Ed. 17', 'OP-OMB-017', 'Curved Barbell', 'Acero 316L quirúrgico · Oro PVD 18k · Sin níquel', 'Corazón Rosa PVD Ed. 17 de la colección Ombligo. Diseño tipo Curved Barbell elaborado en Acero 316L quirúrgico. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 45900, '/images/categorias/Ombligo.png', 10, 'corazon-rosa-pvd-ed-17-17', TRUE),
    ('Estrella Brillante Ed. 18', 'OP-OMB-018', 'Cadena', 'Titanio G23 · Zirconia cúbica AAA · Anodizado', 'Estrella Brillante Ed. 18 de la colección Ombligo. Diseño tipo Cadena elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 48400, '/images/categorias/Ombligo.png', 10, 'estrella-brillante-ed-18-18', TRUE),
    ('Barbell Ombligo Ópalo Ed. 19', 'OP-OMB-019', 'Dangle', 'Acero 316L · Cristal Swarovski · 14g estándar', 'Barbell Ombligo Ópalo Ed. 19 de la colección Ombligo. Diseño tipo Dangle elaborado en Acero 316L. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 50900, '/images/categorias/Ombligo.png', 10, 'barbell-ombligo-opalo-ed-19-19', TRUE),
    ('Cadena Triple Gema Ed. 20', 'OP-OMB-020', 'Reverse', 'Titanio G23 · Disco plano interno · Cierre seguro', 'Cadena Triple Gema Ed. 20 de la colección Ombligo. Diseño tipo Reverse elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 53400, '/images/categorias/Ombligo.png', 10, 'cadena-triple-gema-ed-20-20', TRUE),
    ('Curved Barbell Ceja Cristal', 'OP-CEJ-001', 'Curved', 'Titanio G23 implant-grade · Libre de alérgenos · Hipoalergénico', 'Curved Barbell Ceja Cristal de la colección Ceja. Diseño tipo Curved elaborado en Titanio G23 implant-grade. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 20000, '/images/categorias/Ceja.png', 10, 'curved-barbell-ceja-cristal', TRUE),
    ('Straight Barbell Micro', 'OP-CEJ-002', 'Straight', 'Acero 316L quirúrgico · Oro PVD 18k · Sin níquel', 'Straight Barbell Micro de la colección Ceja. Diseño tipo Straight elaborado en Acero 316L quirúrgico. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 22500, '/images/categorias/Ceja.png', 10, 'straight-barbell-micro', TRUE),
    ('Ceja Anodizada Violeta', 'OP-CEJ-003', 'Micro', 'Titanio G23 · Zirconia cúbica AAA · Anodizado', 'Ceja Anodizada Violeta de la colección Ceja. Diseño tipo Micro elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 25000, '/images/categorias/Ceja.png', 10, 'ceja-anodizada-violeta', TRUE),
    ('Surface Bar Mini', 'OP-CEJ-004', 'Surface', 'Acero 316L · Cristal Swarovski · 14g estándar', 'Surface Bar Mini de la colección Ceja. Diseño tipo Surface elaborado en Acero 316L. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 27500, '/images/categorias/Ceja.png', 10, 'surface-bar-mini', TRUE),
    ('Disco Plano Titanio', 'OP-CEJ-005', 'Anodizado', 'Titanio G23 · Disco plano interno · Cierre seguro', 'Disco Plano Titanio de la colección Ceja. Diseño tipo Anodizado elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 30000, '/images/categorias/Ceja.png', 10, 'disco-plano-titanio', TRUE),
    ('Ceja Gota Zirconia', 'OP-CEJ-006', 'Cristal', 'Titanio G23 implant-grade · Libre de alérgenos · Hipoalergénico', 'Ceja Gota Zirconia de la colección Ceja. Diseño tipo Cristal elaborado en Titanio G23 implant-grade. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 21800, '/images/categorias/Ceja.png', 10, 'ceja-gota-zirconia', TRUE),
    ('Micro Curved Dorado', 'OP-CEJ-007', 'Disco Plano', 'Acero 316L quirúrgico · Oro PVD 18k · Sin níquel', 'Micro Curved Dorado de la colección Ceja. Diseño tipo Disco Plano elaborado en Acero 316L quirúrgico. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 24300, '/images/categorias/Ceja.png', 10, 'micro-curved-dorado', TRUE),
    ('Mini Hoop Ceja', 'OP-CEJ-008', 'Mini Hoop', 'Titanio G23 · Zirconia cúbica AAA · Anodizado', 'Mini Hoop Ceja de la colección Ceja. Diseño tipo Mini Hoop elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 26800, '/images/categorias/Ceja.png', 10, 'mini-hoop-ceja', TRUE),
    ('Ceja Flor Pequeña', 'OP-CEJ-009', 'Curved', 'Acero 316L · Cristal Swarovski · 14g estándar', 'Ceja Flor Pequeña de la colección Ceja. Diseño tipo Curved elaborado en Acero 316L. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 29300, '/images/categorias/Ceja.png', 10, 'ceja-flor-pequena', TRUE),
    ('Barbell Ceja Negro', 'OP-CEJ-010', 'Straight', 'Titanio G23 · Disco plano interno · Cierre seguro', 'Barbell Ceja Negro de la colección Ceja. Diseño tipo Straight elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 31800, '/images/categorias/Ceja.png', 10, 'barbell-ceja-negro', TRUE),
    ('Curved Barbell Ceja Cristal Ed. 11', 'OP-CEJ-011', 'Micro', 'Titanio G23 implant-grade · Libre de alérgenos · Hipoalergénico', 'Curved Barbell Ceja Cristal Ed. 11 de la colección Ceja. Diseño tipo Micro elaborado en Titanio G23 implant-grade. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 23600, '/images/categorias/Ceja.png', 10, 'curved-barbell-ceja-cristal-ed-11-11', TRUE),
    ('Straight Barbell Micro Ed. 12', 'OP-CEJ-012', 'Surface', 'Acero 316L quirúrgico · Oro PVD 18k · Sin níquel', 'Straight Barbell Micro Ed. 12 de la colección Ceja. Diseño tipo Surface elaborado en Acero 316L quirúrgico. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 26100, '/images/categorias/Ceja.png', 10, 'straight-barbell-micro-ed-12-12', TRUE),
    ('Ceja Anodizada Violeta Ed. 13', 'OP-CEJ-013', 'Anodizado', 'Titanio G23 · Zirconia cúbica AAA · Anodizado', 'Ceja Anodizada Violeta Ed. 13 de la colección Ceja. Diseño tipo Anodizado elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 28600, '/images/categorias/Ceja.png', 10, 'ceja-anodizada-violeta-ed-13-13', TRUE),
    ('Surface Bar Mini Ed. 14', 'OP-CEJ-014', 'Cristal', 'Acero 316L · Cristal Swarovski · 14g estándar', 'Surface Bar Mini Ed. 14 de la colección Ceja. Diseño tipo Cristal elaborado en Acero 316L. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 31100, '/images/categorias/Ceja.png', 10, 'surface-bar-mini-ed-14-14', TRUE),
    ('Disco Plano Titanio Ed. 15', 'OP-CEJ-015', 'Disco Plano', 'Titanio G23 · Disco plano interno · Cierre seguro', 'Disco Plano Titanio Ed. 15 de la colección Ceja. Diseño tipo Disco Plano elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 33600, '/images/categorias/Ceja.png', 10, 'disco-plano-titanio-ed-15-15', TRUE),
    ('Ceja Gota Zirconia Ed. 16', 'OP-CEJ-016', 'Mini Hoop', 'Titanio G23 implant-grade · Libre de alérgenos · Hipoalergénico', 'Ceja Gota Zirconia Ed. 16 de la colección Ceja. Diseño tipo Mini Hoop elaborado en Titanio G23 implant-grade. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 25400, '/images/categorias/Ceja.png', 10, 'ceja-gota-zirconia-ed-16-16', TRUE),
    ('Micro Curved Dorado Ed. 17', 'OP-CEJ-017', 'Curved', 'Acero 316L quirúrgico · Oro PVD 18k · Sin níquel', 'Micro Curved Dorado Ed. 17 de la colección Ceja. Diseño tipo Curved elaborado en Acero 316L quirúrgico. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 27900, '/images/categorias/Ceja.png', 10, 'micro-curved-dorado-ed-17-17', TRUE),
    ('Mini Hoop Ceja Ed. 18', 'OP-CEJ-018', 'Straight', 'Titanio G23 · Zirconia cúbica AAA · Anodizado', 'Mini Hoop Ceja Ed. 18 de la colección Ceja. Diseño tipo Straight elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 30400, '/images/categorias/Ceja.png', 10, 'mini-hoop-ceja-ed-18-18', TRUE),
    ('Ceja Flor Pequeña Ed. 19', 'OP-CEJ-019', 'Micro', 'Acero 316L · Cristal Swarovski · 14g estándar', 'Ceja Flor Pequeña Ed. 19 de la colección Ceja. Diseño tipo Micro elaborado en Acero 316L. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 32900, '/images/categorias/Ceja.png', 10, 'ceja-flor-pequena-ed-19-19', TRUE),
    ('Barbell Ceja Negro Ed. 20', 'OP-CEJ-020', 'Surface', 'Titanio G23 · Disco plano interno · Cierre seguro', 'Barbell Ceja Negro Ed. 20 de la colección Ceja. Diseño tipo Surface elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 35400, '/images/categorias/Ceja.png', 10, 'barbell-ceja-negro-ed-20-20', TRUE),
    ('Labret Disco Plano', 'OP-LAB-001', 'Labret', 'Titanio G23 implant-grade · Libre de alérgenos · Hipoalergénico', 'Labret Disco Plano de la colección Labio. Diseño tipo Labret elaborado en Titanio G23 implant-grade. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 21000, '/images/categorias/Labio.png', 10, 'labret-disco-plano', TRUE),
    ('Monroe con Zirconia', 'OP-LAB-002', 'Monroe', 'Acero 316L quirúrgico · Oro PVD 18k · Sin níquel', 'Monroe con Zirconia de la colección Labio. Diseño tipo Monroe elaborado en Acero 316L quirúrgico. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 23500, '/images/categorias/Labio.png', 10, 'monroe-con-zirconia', TRUE),
    ('Medusa Cristal', 'OP-LAB-003', 'Medusa', 'Titanio G23 · Zirconia cúbica AAA · Anodizado', 'Medusa Cristal de la colección Labio. Diseño tipo Medusa elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 26000, '/images/categorias/Labio.png', 10, 'medusa-cristal', TRUE),
    ('Snake Bites Par Dorado', 'OP-LAB-004', 'Snake Bites', 'Acero 316L · Cristal Swarovski · 14g estándar', 'Snake Bites Par Dorado de la colección Labio. Diseño tipo Snake Bites elaborado en Acero 316L. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 28500, '/images/categorias/Labio.png', 10, 'snake-bites-par-dorado', TRUE),
    ('Ashley Barbell Mini', 'OP-LAB-005', 'Ashley', 'Titanio G23 · Disco plano interno · Cierre seguro', 'Ashley Barbell Mini de la colección Labio. Diseño tipo Ashley elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 31000, '/images/categorias/Labio.png', 10, 'ashley-barbell-mini', TRUE),
    ('Vertical Labret Titanio', 'OP-LAB-006', 'Vertical', 'Titanio G23 implant-grade · Libre de alérgenos · Hipoalergénico', 'Vertical Labret Titanio de la colección Labio. Diseño tipo Vertical elaborado en Titanio G23 implant-grade. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 22800, '/images/categorias/Labio.png', 10, 'vertical-labret-titanio', TRUE),
    ('Labret Ópalo Rosa', 'OP-LAB-007', 'Disco Interno', 'Acero 316L quirúrgico · Oro PVD 18k · Sin níquel', 'Labret Ópalo Rosa de la colección Labio. Diseño tipo Disco Interno elaborado en Acero 316L quirúrgico. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 25300, '/images/categorias/Labio.png', 10, 'labret-opalo-rosa', TRUE),
    ('Monroe Perla Cultivada', 'OP-LAB-008', 'Gema', 'Titanio G23 · Zirconia cúbica AAA · Anodizado', 'Monroe Perla Cultivada de la colección Labio. Diseño tipo Gema elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 27800, '/images/categorias/Labio.png', 10, 'monroe-perla-cultivada', TRUE),
    ('Labret Corazón Mini', 'OP-LAB-009', 'Labret', 'Acero 316L · Cristal Swarovski · 14g estándar', 'Labret Corazón Mini de la colección Labio. Diseño tipo Labret elaborado en Acero 316L. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 30300, '/images/categorias/Labio.png', 10, 'labret-corazon-mini', TRUE),
    ('Medusa Estrella', 'OP-LAB-010', 'Monroe', 'Titanio G23 · Disco plano interno · Cierre seguro', 'Medusa Estrella de la colección Labio. Diseño tipo Monroe elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 32800, '/images/categorias/Labio.png', 10, 'medusa-estrella', TRUE),
    ('Labret Disco Plano Ed. 11', 'OP-LAB-011', 'Medusa', 'Titanio G23 implant-grade · Libre de alérgenos · Hipoalergénico', 'Labret Disco Plano Ed. 11 de la colección Labio. Diseño tipo Medusa elaborado en Titanio G23 implant-grade. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 24600, '/images/categorias/Labio.png', 10, 'labret-disco-plano-ed-11-11', TRUE),
    ('Monroe con Zirconia Ed. 12', 'OP-LAB-012', 'Snake Bites', 'Acero 316L quirúrgico · Oro PVD 18k · Sin níquel', 'Monroe con Zirconia Ed. 12 de la colección Labio. Diseño tipo Snake Bites elaborado en Acero 316L quirúrgico. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 27100, '/images/categorias/Labio.png', 10, 'monroe-con-zirconia-ed-12-12', TRUE),
    ('Medusa Cristal Ed. 13', 'OP-LAB-013', 'Ashley', 'Titanio G23 · Zirconia cúbica AAA · Anodizado', 'Medusa Cristal Ed. 13 de la colección Labio. Diseño tipo Ashley elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 29600, '/images/categorias/Labio.png', 10, 'medusa-cristal-ed-13-13', TRUE),
    ('Snake Bites Par Dorado Ed. 14', 'OP-LAB-014', 'Vertical', 'Acero 316L · Cristal Swarovski · 14g estándar', 'Snake Bites Par Dorado Ed. 14 de la colección Labio. Diseño tipo Vertical elaborado en Acero 316L. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 32100, '/images/categorias/Labio.png', 10, 'snake-bites-par-dorado-ed-14-14', TRUE),
    ('Ashley Barbell Mini Ed. 15', 'OP-LAB-015', 'Disco Interno', 'Titanio G23 · Disco plano interno · Cierre seguro', 'Ashley Barbell Mini Ed. 15 de la colección Labio. Diseño tipo Disco Interno elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 34600, '/images/categorias/Labio.png', 10, 'ashley-barbell-mini-ed-15-15', TRUE),
    ('Vertical Labret Titanio Ed. 16', 'OP-LAB-016', 'Gema', 'Titanio G23 implant-grade · Libre de alérgenos · Hipoalergénico', 'Vertical Labret Titanio Ed. 16 de la colección Labio. Diseño tipo Gema elaborado en Titanio G23 implant-grade. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 26400, '/images/categorias/Labio.png', 10, 'vertical-labret-titanio-ed-16-16', TRUE),
    ('Labret Ópalo Rosa Ed. 17', 'OP-LAB-017', 'Labret', 'Acero 316L quirúrgico · Oro PVD 18k · Sin níquel', 'Labret Ópalo Rosa Ed. 17 de la colección Labio. Diseño tipo Labret elaborado en Acero 316L quirúrgico. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 28900, '/images/categorias/Labio.png', 10, 'labret-opalo-rosa-ed-17-17', TRUE),
    ('Monroe Perla Cultivada Ed. 18', 'OP-LAB-018', 'Monroe', 'Titanio G23 · Zirconia cúbica AAA · Anodizado', 'Monroe Perla Cultivada Ed. 18 de la colección Labio. Diseño tipo Monroe elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 31400, '/images/categorias/Labio.png', 10, 'monroe-perla-cultivada-ed-18-18', TRUE),
    ('Labret Corazón Mini Ed. 19', 'OP-LAB-019', 'Medusa', 'Acero 316L · Cristal Swarovski · 14g estándar', 'Labret Corazón Mini Ed. 19 de la colección Labio. Diseño tipo Medusa elaborado en Acero 316L. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 33900, '/images/categorias/Labio.png', 10, 'labret-corazon-mini-ed-19-19', TRUE),
    ('Medusa Estrella Ed. 20', 'OP-LAB-020', 'Snake Bites', 'Titanio G23 · Disco plano interno · Cierre seguro', 'Medusa Estrella Ed. 20 de la colección Labio. Diseño tipo Snake Bites elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 36400, '/images/categorias/Labio.png', 10, 'medusa-estrella-ed-20-20', TRUE),
    ('Industrial Bar Minimalista', 'OP-IND-001', 'Barbell', 'Titanio G23 implant-grade · Libre de alérgenos · Hipoalergénico', 'Industrial Bar Minimalista de la colección Industrial. Diseño tipo Barbell elaborado en Titanio G23 implant-grade. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 36000, '/images/categorias/industrial.png', 10, 'industrial-bar-minimalista', TRUE),
    ('Industrial con Opalitos', 'OP-IND-002', 'Gemas', 'Acero 316L quirúrgico · Oro PVD 18k · Sin níquel', 'Industrial con Opalitos de la colección Industrial. Diseño tipo Gemas elaborado en Acero 316L quirúrgico. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 38500, '/images/categorias/industrial.png', 10, 'industrial-con-opalitos', TRUE),
    ('Bar Industrial Cristal', 'OP-IND-003', 'Minimalista', 'Titanio G23 · Zirconia cúbica AAA · Anodizado', 'Bar Industrial Cristal de la colección Industrial. Diseño tipo Minimalista elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 41000, '/images/categorias/industrial.png', 10, 'bar-industrial-cristal', TRUE),
    ('Industrial Negro Mate', 'OP-IND-004', 'Opalitos', 'Acero 316L · Cristal Swarovski · 14g estándar', 'Industrial Negro Mate de la colección Industrial. Diseño tipo Opalitos elaborado en Acero 316L. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 43500, '/images/categorias/industrial.png', 10, 'industrial-negro-mate', TRUE),
    ('Industrial Dorado PVD', 'OP-IND-005', 'Cadenas', 'Titanio G23 · Disco plano interno · Cierre seguro', 'Industrial Dorado PVD de la colección Industrial. Diseño tipo Cadenas elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 46000, '/images/categorias/industrial.png', 10, 'industrial-dorado-pvd', TRUE),
    ('Industrial Gemas Triple', 'OP-IND-006', 'Cristal', 'Titanio G23 implant-grade · Libre de alérgenos · Hipoalergénico', 'Industrial Gemas Triple de la colección Industrial. Diseño tipo Cristal elaborado en Titanio G23 implant-grade. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 37800, '/images/categorias/industrial.png', 10, 'industrial-gemas-triple', TRUE),
    ('Barbell Industrial 38mm', 'OP-IND-007', 'Negro', 'Acero 316L quirúrgico · Oro PVD 18k · Sin níquel', 'Barbell Industrial 38mm de la colección Industrial. Diseño tipo Negro elaborado en Acero 316L quirúrgico. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 40300, '/images/categorias/industrial.png', 10, 'barbell-industrial-38mm', TRUE),
    ('Industrial Luna y Sol', 'OP-IND-008', 'Dorado', 'Titanio G23 · Zirconia cúbica AAA · Anodizado', 'Industrial Luna y Sol de la colección Industrial. Diseño tipo Dorado elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 42800, '/images/categorias/industrial.png', 10, 'industrial-luna-y-sol', TRUE),
    ('Industrial Cadena Mini', 'OP-IND-009', 'Barbell', 'Acero 316L · Cristal Swarovski · 14g estándar', 'Industrial Cadena Mini de la colección Industrial. Diseño tipo Barbell elaborado en Acero 316L. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 45300, '/images/categorias/industrial.png', 10, 'industrial-cadena-mini', TRUE),
    ('Industrial Zirconia Central', 'OP-IND-010', 'Gemas', 'Titanio G23 · Disco plano interno · Cierre seguro', 'Industrial Zirconia Central de la colección Industrial. Diseño tipo Gemas elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 47800, '/images/categorias/industrial.png', 10, 'industrial-zirconia-central', TRUE),
    ('Industrial Bar Minimalista Ed. 11', 'OP-IND-011', 'Minimalista', 'Titanio G23 implant-grade · Libre de alérgenos · Hipoalergénico', 'Industrial Bar Minimalista Ed. 11 de la colección Industrial. Diseño tipo Minimalista elaborado en Titanio G23 implant-grade. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 39600, '/images/categorias/industrial.png', 10, 'industrial-bar-minimalista-ed-11-11', TRUE),
    ('Industrial con Opalitos Ed. 12', 'OP-IND-012', 'Opalitos', 'Acero 316L quirúrgico · Oro PVD 18k · Sin níquel', 'Industrial con Opalitos Ed. 12 de la colección Industrial. Diseño tipo Opalitos elaborado en Acero 316L quirúrgico. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 42100, '/images/categorias/industrial.png', 10, 'industrial-con-opalitos-ed-12-12', TRUE),
    ('Bar Industrial Cristal Ed. 13', 'OP-IND-013', 'Cadenas', 'Titanio G23 · Zirconia cúbica AAA · Anodizado', 'Bar Industrial Cristal Ed. 13 de la colección Industrial. Diseño tipo Cadenas elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 44600, '/images/categorias/industrial.png', 10, 'bar-industrial-cristal-ed-13-13', TRUE),
    ('Industrial Negro Mate Ed. 14', 'OP-IND-014', 'Cristal', 'Acero 316L · Cristal Swarovski · 14g estándar', 'Industrial Negro Mate Ed. 14 de la colección Industrial. Diseño tipo Cristal elaborado en Acero 316L. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 47100, '/images/categorias/industrial.png', 10, 'industrial-negro-mate-ed-14-14', TRUE),
    ('Industrial Dorado PVD Ed. 15', 'OP-IND-015', 'Negro', 'Titanio G23 · Disco plano interno · Cierre seguro', 'Industrial Dorado PVD Ed. 15 de la colección Industrial. Diseño tipo Negro elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 49600, '/images/categorias/industrial.png', 10, 'industrial-dorado-pvd-ed-15-15', TRUE),
    ('Industrial Gemas Triple Ed. 16', 'OP-IND-016', 'Dorado', 'Titanio G23 implant-grade · Libre de alérgenos · Hipoalergénico', 'Industrial Gemas Triple Ed. 16 de la colección Industrial. Diseño tipo Dorado elaborado en Titanio G23 implant-grade. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 41400, '/images/categorias/industrial.png', 10, 'industrial-gemas-triple-ed-16-16', TRUE),
    ('Barbell Industrial 38mm Ed. 17', 'OP-IND-017', 'Barbell', 'Acero 316L quirúrgico · Oro PVD 18k · Sin níquel', 'Barbell Industrial 38mm Ed. 17 de la colección Industrial. Diseño tipo Barbell elaborado en Acero 316L quirúrgico. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 43900, '/images/categorias/industrial.png', 10, 'barbell-industrial-38mm-ed-17-17', TRUE),
    ('Industrial Luna y Sol Ed. 18', 'OP-IND-018', 'Gemas', 'Titanio G23 · Zirconia cúbica AAA · Anodizado', 'Industrial Luna y Sol Ed. 18 de la colección Industrial. Diseño tipo Gemas elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 46400, '/images/categorias/industrial.png', 10, 'industrial-luna-y-sol-ed-18-18', TRUE),
    ('Industrial Cadena Mini Ed. 19', 'OP-IND-019', 'Minimalista', 'Acero 316L · Cristal Swarovski · 14g estándar', 'Industrial Cadena Mini Ed. 19 de la colección Industrial. Diseño tipo Minimalista elaborado en Acero 316L. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 48900, '/images/categorias/industrial.png', 10, 'industrial-cadena-mini-ed-19-19', TRUE),
    ('Industrial Zirconia Central Ed. 20', 'OP-IND-020', 'Opalitos', 'Titanio G23 · Disco plano interno · Cierre seguro', 'Industrial Zirconia Central Ed. 20 de la colección Industrial. Diseño tipo Opalitos elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 51400, '/images/categorias/industrial.png', 10, 'industrial-zirconia-central-ed-20-20', TRUE),
    ('Barbell Lengua Titanio G23', 'OP-LEN-001', 'Straight Barbell', 'Titanio G23 implant-grade · Libre de alérgenos · Hipoalergénico', 'Barbell Lengua Titanio G23 de la colección Lengua. Diseño tipo Straight Barbell elaborado en Titanio G23 implant-grade. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 22000, '/images/categorias/Lengua.png', 10, 'barbell-lengua-titanio-g23', TRUE),
    ('Barbell con Bolas de Zirconia', 'OP-LEN-002', 'Gem Barbell', 'Acero 316L quirúrgico · Oro PVD 18k · Sin níquel', 'Barbell con Bolas de Zirconia de la colección Lengua. Diseño tipo Gem Barbell elaborado en Acero 316L quirúrgico. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 24500, '/images/categorias/Lengua.png', 10, 'barbell-con-bolas-de-zirconia', TRUE),
    ('Barbell Anodizado Arcoíris', 'OP-LEN-003', 'Anodizado', 'Titanio G23 · Zirconia cúbica AAA · Anodizado', 'Barbell Anodizado Arcoíris de la colección Lengua. Diseño tipo Anodizado elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 27000, '/images/categorias/Lengua.png', 10, 'barbell-anodizado-arcoiris', TRUE),
    ('Barbell Bioflex Transparente', 'OP-LEN-004', 'Bioflex', 'Acero 316L · Cristal Swarovski · 14g estándar', 'Barbell Bioflex Transparente de la colección Lengua. Diseño tipo Bioflex elaborado en Acero 316L. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 29500, '/images/categorias/Lengua.png', 10, 'barbell-bioflex-transparente', TRUE),
    ('Barbell UV Reactive Neon', 'OP-LEN-005', 'Bolas Cristal', 'Titanio G23 · Disco plano interno · Cierre seguro', 'Barbell UV Reactive Neon de la colección Lengua. Diseño tipo Bolas Cristal elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 32000, '/images/categorias/Lengua.png', 10, 'barbell-uv-reactive-neon', TRUE),
    ('Barbell Bolas de Ópalo', 'OP-LEN-006', 'UV Reactive', 'Titanio G23 implant-grade · Libre de alérgenos · Hipoalergénico', 'Barbell Bolas de Ópalo de la colección Lengua. Diseño tipo UV Reactive elaborado en Titanio G23 implant-grade. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 23800, '/images/categorias/Lengua.png', 10, 'barbell-bolas-de-opalo', TRUE),
    ('Barbell Lengua Dorado PVD', 'OP-LEN-007', 'Ópalo', 'Acero 316L quirúrgico · Oro PVD 18k · Sin níquel', 'Barbell Lengua Dorado PVD de la colección Lengua. Diseño tipo Ópalo elaborado en Acero 316L quirúrgico. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 26300, '/images/categorias/Lengua.png', 10, 'barbell-lengua-dorado-pvd', TRUE),
    ('Barbell Mini 12g Delgado', 'OP-LEN-008', 'Dorado PVD', 'Titanio G23 · Zirconia cúbica AAA · Anodizado', 'Barbell Mini 12g Delgado de la colección Lengua. Diseño tipo Dorado PVD elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 28800, '/images/categorias/Lengua.png', 10, 'barbell-mini-12g-delgado', TRUE),
    ('Barbell con Diamante Sintético', 'OP-LEN-009', 'Straight Barbell', 'Acero 316L · Cristal Swarovski · 14g estándar', 'Barbell con Diamante Sintético de la colección Lengua. Diseño tipo Straight Barbell elaborado en Acero 316L. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 31300, '/images/categorias/Lengua.png', 10, 'barbell-con-diamante-sintetico', TRUE),
    ('Barbell Lengua Negro Anodizado', 'OP-LEN-010', 'Gem Barbell', 'Titanio G23 · Disco plano interno · Cierre seguro', 'Barbell Lengua Negro Anodizado de la colección Lengua. Diseño tipo Gem Barbell elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 33800, '/images/categorias/Lengua.png', 10, 'barbell-lengua-negro-anodizado', TRUE),
    ('Barbell Lengua Titanio G23 Ed. 11', 'OP-LEN-011', 'Anodizado', 'Titanio G23 implant-grade · Libre de alérgenos · Hipoalergénico', 'Barbell Lengua Titanio G23 Ed. 11 de la colección Lengua. Diseño tipo Anodizado elaborado en Titanio G23 implant-grade. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 25600, '/images/categorias/Lengua.png', 10, 'barbell-lengua-titanio-g23-ed-11-11', TRUE),
    ('Barbell con Bolas de Zirconia Ed. 12', 'OP-LEN-012', 'Bioflex', 'Acero 316L quirúrgico · Oro PVD 18k · Sin níquel', 'Barbell con Bolas de Zirconia Ed. 12 de la colección Lengua. Diseño tipo Bioflex elaborado en Acero 316L quirúrgico. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 28100, '/images/categorias/Lengua.png', 10, 'barbell-con-bolas-de-zirconia-ed-12-12', TRUE),
    ('Barbell Anodizado Arcoíris Ed. 13', 'OP-LEN-013', 'Bolas Cristal', 'Titanio G23 · Zirconia cúbica AAA · Anodizado', 'Barbell Anodizado Arcoíris Ed. 13 de la colección Lengua. Diseño tipo Bolas Cristal elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 30600, '/images/categorias/Lengua.png', 10, 'barbell-anodizado-arcoiris-ed-13-13', TRUE),
    ('Barbell Bioflex Transparente Ed. 14', 'OP-LEN-014', 'UV Reactive', 'Acero 316L · Cristal Swarovski · 14g estándar', 'Barbell Bioflex Transparente Ed. 14 de la colección Lengua. Diseño tipo UV Reactive elaborado en Acero 316L. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 33100, '/images/categorias/Lengua.png', 10, 'barbell-bioflex-transparente-ed-14-14', TRUE),
    ('Barbell UV Reactive Neon Ed. 15', 'OP-LEN-015', 'Ópalo', 'Titanio G23 · Disco plano interno · Cierre seguro', 'Barbell UV Reactive Neon Ed. 15 de la colección Lengua. Diseño tipo Ópalo elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 35600, '/images/categorias/Lengua.png', 10, 'barbell-uv-reactive-neon-ed-15-15', TRUE),
    ('Barbell Bolas de Ópalo Ed. 16', 'OP-LEN-016', 'Dorado PVD', 'Titanio G23 implant-grade · Libre de alérgenos · Hipoalergénico', 'Barbell Bolas de Ópalo Ed. 16 de la colección Lengua. Diseño tipo Dorado PVD elaborado en Titanio G23 implant-grade. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 27400, '/images/categorias/Lengua.png', 10, 'barbell-bolas-de-opalo-ed-16-16', TRUE),
    ('Barbell Lengua Dorado PVD Ed. 17', 'OP-LEN-017', 'Straight Barbell', 'Acero 316L quirúrgico · Oro PVD 18k · Sin níquel', 'Barbell Lengua Dorado PVD Ed. 17 de la colección Lengua. Diseño tipo Straight Barbell elaborado en Acero 316L quirúrgico. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 29900, '/images/categorias/Lengua.png', 10, 'barbell-lengua-dorado-pvd-ed-17-17', TRUE),
    ('Barbell Mini 12g Delgado Ed. 18', 'OP-LEN-018', 'Gem Barbell', 'Titanio G23 · Zirconia cúbica AAA · Anodizado', 'Barbell Mini 12g Delgado Ed. 18 de la colección Lengua. Diseño tipo Gem Barbell elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 32400, '/images/categorias/Lengua.png', 10, 'barbell-mini-12g-delgado-ed-18-18', TRUE),
    ('Barbell con Diamante Sintético Ed. 19', 'OP-LEN-019', 'Anodizado', 'Acero 316L · Cristal Swarovski · 14g estándar', 'Barbell con Diamante Sintético Ed. 19 de la colección Lengua. Diseño tipo Anodizado elaborado en Acero 316L. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 34900, '/images/categorias/Lengua.png', 10, 'barbell-con-diamante-sintetico-ed-19-19', TRUE),
    ('Barbell Lengua Negro Anodizado Ed. 20', 'OP-LEN-020', 'Bioflex', 'Titanio G23 · Disco plano interno · Cierre seguro', 'Barbell Lengua Negro Anodizado Ed. 20 de la colección Lengua. Diseño tipo Bioflex elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 37400, '/images/categorias/Lengua.png', 10, 'barbell-lengua-negro-anodizado-ed-20-20', TRUE),
    ('Barbell Pesón Titanio', 'OP-PES-001', 'Barbell', 'Titanio G23 implant-grade · Libre de alérgenos · Hipoalergénico', 'Barbell Pesón Titanio de la colección Pesones. Diseño tipo Barbell elaborado en Titanio G23 implant-grade. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 32000, '/images/categorias/pesona.png', 10, 'barbell-peson-titanio', TRUE),
    ('Aro Pesón Acero 316L', 'OP-PES-002', 'Aro', 'Acero 316L quirúrgico · Oro PVD 18k · Sin níquel', 'Aro Pesón Acero 316L de la colección Pesones. Diseño tipo Aro elaborado en Acero 316L quirúrgico. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 34500, '/images/categorias/pesona.png', 10, 'aro-peson-acero-316l', TRUE),
    ('Escudo Pesón con Gema', 'OP-PES-003', 'Escudo', 'Titanio G23 · Zirconia cúbica AAA · Anodizado', 'Escudo Pesón con Gema de la colección Pesones. Diseño tipo Escudo elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 37000, '/images/categorias/pesona.png', 10, 'escudo-peson-con-gema', TRUE),
    ('Barbell Pesón Zirconia', 'OP-PES-004', 'Gem Barbell', 'Acero 316L · Cristal Swarovski · 14g estándar', 'Barbell Pesón Zirconia de la colección Pesones. Diseño tipo Gem Barbell elaborado en Acero 316L. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 39500, '/images/categorias/pesona.png', 10, 'barbell-peson-zirconia', TRUE),
    ('Aro Captive Bead Pesón', 'OP-PES-005', 'Captive Bead', 'Titanio G23 · Disco plano interno · Cierre seguro', 'Aro Captive Bead Pesón de la colección Pesones. Diseño tipo Captive Bead elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 42000, '/images/categorias/pesona.png', 10, 'aro-captive-bead-peson', TRUE),
    ('Barbell Pesón Oro Rosa PVD', 'OP-PES-006', 'Clicker', 'Titanio G23 implant-grade · Libre de alérgenos · Hipoalergénico', 'Barbell Pesón Oro Rosa PVD de la colección Pesones. Diseño tipo Clicker elaborado en Titanio G23 implant-grade. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 33800, '/images/categorias/pesona.png', 10, 'barbell-peson-oro-rosa-pvd', TRUE),
    ('Escudo Flor de Cristal', 'OP-PES-007', 'Flor', 'Acero 316L quirúrgico · Oro PVD 18k · Sin níquel', 'Escudo Flor de Cristal de la colección Pesones. Diseño tipo Flor elaborado en Acero 316L quirúrgico. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 36300, '/images/categorias/pesona.png', 10, 'escudo-flor-de-cristal', TRUE),
    ('Barbell Pesón 14g Estándar', 'OP-PES-008', 'Corazón', 'Titanio G23 · Zirconia cúbica AAA · Anodizado', 'Barbell Pesón 14g Estándar de la colección Pesones. Diseño tipo Corazón elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 38800, '/images/categorias/pesona.png', 10, 'barbell-peson-14g-estandar', TRUE),
    ('Aro Pesón Clicker', 'OP-PES-009', 'Barbell', 'Acero 316L · Cristal Swarovski · 14g estándar', 'Aro Pesón Clicker de la colección Pesones. Diseño tipo Barbell elaborado en Acero 316L. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 41300, '/images/categorias/pesona.png', 10, 'aro-peson-clicker', TRUE),
    ('Barbell Pesón Estilo Industrial', 'OP-PES-010', 'Aro', 'Titanio G23 · Disco plano interno · Cierre seguro', 'Barbell Pesón Estilo Industrial de la colección Pesones. Diseño tipo Aro elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 43800, '/images/categorias/pesona.png', 10, 'barbell-peson-estilo-industrial', TRUE),
    ('Barbell Pesón Titanio Ed. 11', 'OP-PES-011', 'Escudo', 'Titanio G23 implant-grade · Libre de alérgenos · Hipoalergénico', 'Barbell Pesón Titanio Ed. 11 de la colección Pesones. Diseño tipo Escudo elaborado en Titanio G23 implant-grade. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 35600, '/images/categorias/pesona.png', 10, 'barbell-peson-titanio-ed-11-11', TRUE),
    ('Aro Pesón Acero 316L Ed. 12', 'OP-PES-012', 'Gem Barbell', 'Acero 316L quirúrgico · Oro PVD 18k · Sin níquel', 'Aro Pesón Acero 316L Ed. 12 de la colección Pesones. Diseño tipo Gem Barbell elaborado en Acero 316L quirúrgico. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 38100, '/images/categorias/pesona.png', 10, 'aro-peson-acero-316l-ed-12-12', TRUE),
    ('Escudo Pesón con Gema Ed. 13', 'OP-PES-013', 'Captive Bead', 'Titanio G23 · Zirconia cúbica AAA · Anodizado', 'Escudo Pesón con Gema Ed. 13 de la colección Pesones. Diseño tipo Captive Bead elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 40600, '/images/categorias/pesona.png', 10, 'escudo-peson-con-gema-ed-13-13', TRUE),
    ('Barbell Pesón Zirconia Ed. 14', 'OP-PES-014', 'Clicker', 'Acero 316L · Cristal Swarovski · 14g estándar', 'Barbell Pesón Zirconia Ed. 14 de la colección Pesones. Diseño tipo Clicker elaborado en Acero 316L. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 43100, '/images/categorias/pesona.png', 10, 'barbell-peson-zirconia-ed-14-14', TRUE),
    ('Aro Captive Bead Pesón Ed. 15', 'OP-PES-015', 'Flor', 'Titanio G23 · Disco plano interno · Cierre seguro', 'Aro Captive Bead Pesón Ed. 15 de la colección Pesones. Diseño tipo Flor elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 45600, '/images/categorias/pesona.png', 10, 'aro-captive-bead-peson-ed-15-15', TRUE),
    ('Barbell Pesón Oro Rosa PVD Ed. 16', 'OP-PES-016', 'Corazón', 'Titanio G23 implant-grade · Libre de alérgenos · Hipoalergénico', 'Barbell Pesón Oro Rosa PVD Ed. 16 de la colección Pesones. Diseño tipo Corazón elaborado en Titanio G23 implant-grade. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 37400, '/images/categorias/pesona.png', 10, 'barbell-peson-oro-rosa-pvd-ed-16-16', TRUE),
    ('Escudo Flor de Cristal Ed. 17', 'OP-PES-017', 'Barbell', 'Acero 316L quirúrgico · Oro PVD 18k · Sin níquel', 'Escudo Flor de Cristal Ed. 17 de la colección Pesones. Diseño tipo Barbell elaborado en Acero 316L quirúrgico. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 39900, '/images/categorias/pesona.png', 10, 'escudo-flor-de-cristal-ed-17-17', TRUE),
    ('Barbell Pesón 14g Estándar Ed. 18', 'OP-PES-018', 'Aro', 'Titanio G23 · Zirconia cúbica AAA · Anodizado', 'Barbell Pesón 14g Estándar Ed. 18 de la colección Pesones. Diseño tipo Aro elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 42400, '/images/categorias/pesona.png', 10, 'barbell-peson-14g-estandar-ed-18-18', TRUE),
    ('Aro Pesón Clicker Ed. 19', 'OP-PES-019', 'Escudo', 'Acero 316L · Cristal Swarovski · 14g estándar', 'Aro Pesón Clicker Ed. 19 de la colección Pesones. Diseño tipo Escudo elaborado en Acero 316L. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 44900, '/images/categorias/pesona.png', 10, 'aro-peson-clicker-ed-19-19', TRUE),
    ('Barbell Pesón Estilo Industrial Ed. 20', 'OP-PES-020', 'Gem Barbell', 'Titanio G23 · Disco plano interno · Cierre seguro', 'Barbell Pesón Estilo Industrial Ed. 20 de la colección Pesones. Diseño tipo Gem Barbell elaborado en Titanio G23. Acabado premium, empaque estéril individual y guía de cuidados incluida. Envío seguro a todo Colombia con asesoría personalizada por WhatsApp.', 47400, '/images/categorias/pesona.png', 10, 'barbell-peson-estilo-industrial-ed-20-20', TRUE)
) AS v(nombre, codigo, tipo, material, descripcion, precio, imagen, stock, slug, activo)
WHERE NOT EXISTS (SELECT 1 FROM productos p WHERE p.codigo = v.codigo);

INSERT INTO producto_categorias (producto_id, categoria_id)
SELECT p.id, c.id
FROM productos p
JOIN categorias c ON c.slug = CASE
  WHEN p.codigo LIKE 'OP-NAR-%' THEN 'nariz'
  WHEN p.codigo LIKE 'OP-OMB-%' THEN 'ombligo'
  WHEN p.codigo LIKE 'OP-CEJ-%' THEN 'ceja'
  WHEN p.codigo LIKE 'OP-LAB-%' THEN 'labio'
  WHEN p.codigo LIKE 'OP-IND-%' THEN 'industrial'
  WHEN p.codigo LIKE 'OP-LEN-%' THEN 'lengua'
  WHEN p.codigo LIKE 'OP-PES-%' THEN 'pesones'
END
WHERE p.codigo ~ '^OP-(NAR|OMB|CEJ|LAB|IND|LEN|PES)-'
  AND NOT EXISTS (
    SELECT 1 FROM producto_categorias pc
    WHERE pc.producto_id = p.id AND pc.categoria_id = c.id
  );

COMMIT;
